ALTER TABLE "trip" ALTER COLUMN "id" SET DATA TYPE integer USING id::integer;--> statement-breakpoint
ALTER TABLE "trip" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "trip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
